entity_mapper: com.example.demo.entity
jdbc:
  driver: com.mysql.jdbc.Driver
  password: qwer1234
  url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: twj
mapper_path: /mapper/**.xml
mybatis_config_file: mybatis-config.xml
server:
  port: 8082
  servlet:
    context-path: /demo
